version: "3"
services:
  homeassistant:
    container_name: homeassistant
    build: .
    volumes:
      - ./hass-config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
