name: Main CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18.x', '20.x', '21.x']
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run test

  e2e-test:
    runs-on: ubuntu-latest
    name: Run E2E tests
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 21.x
      uses: actions/setup-node@v3
      with:
        node-version: 21.x
        cache: 'npm'
    - run: npm install
    - run: npm run test:e2e
      env:
        RTM_API_KEY: ${{ secrets.RTM_API_KEY }}
        RTM_API_SECRET : ${{ secrets.RTM_API_SECRET }}


  checks:
    runs-on: ubuntu-latest
    name: Run static checks
    strategy:
      fail-fast: false
      matrix:
        check: [api-check, build, lint]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run ${{ matrix.check }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test, checks, e2e-test]

    steps:
      - uses: actions/checkout@v3
      - name: Configure node 21.x 
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: yarn install

      - name: Build Package
        run: yarn build

      - name: Release
        id: do-release
        uses: cycjimmy/semantic-release-action@v3.4.0
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  e2e-test-post-release:
    runs-on: ubuntu-latest
    name: Run Post-release E2E tests
    needs: [release]
    if: needs.release.outputs.new_release_published	== 'true'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 21.x
      uses: actions/setup-node@v3
      with:
        node-version: 21.x
        cache: 'npm'
    - run: npm install
    - run: npm run test:e2e:post-release
      env:
        RTM_API_KEY: ${{ secrets.RTM_API_KEY }}
        RTM_API_SECRET : ${{ secrets.RTM_API_SECRET }}

